language: node_js
node_js:
  - lts/*

os:
  - linux
dist: focal

cache: yarn

install: yarn install

script:
  - yarn build
  - yarn generate

branches:
  only:
    - main

deploy:
  provider: pages
  repo: atjhoendz/atjhoendz.github.io
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  on:
    branch: main
