language: node_js
node_js:
  - 'node'

cache: yarn

script: yarn build

deploy:
  provider: pages
  repo: atjhoendz/atjhoendz.github.io
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  on:
    branch: main
